AWSTemplateFormatVersion: '2010-09-09'
Resources:
  PacktFunction:
    Properties:
      CodeUri: s3://packtdemo/f45c4442ea6e464b952d6987c7652f9c
      Environment:
        Variables:
          S3_BUCKET: packtdemo
      Handler: index.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
